# Generated by Django 5.2.1 on 2025-05-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("slug_kat", models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Artikel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("isi", models.TextField()),
                ("slug_art", models.SlugField(blank=True, editable=False)),
                ("pupdate", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "Kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.kategori"
                    ),
                ),
            ],
        ),
    ]
