# Generated by Django 5.2.1 on 2025-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KontakModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("pesan", models.TextField()),
            ],
        ),
    ]
