# Generated by Django 5.2.1 on 2025-05-19 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontak", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kontakmodel",
            name="waktu_kirim",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
